swagger: '2.0'
info:
  title: API Monitoring Reports
  description: API for monitoring reports
  version: 1.0
consumes:
  - application/json
produces:
  - application/json
path:
  /reports:
    get:
      summary: Get all reports
      description: Get all reports
      operationId: getReports
      tags:
        - Reports
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              version:
                type: string
  /reports/{id}:
    get:
      summary: Get report by id
      description: Get report by id
      operationId: getReportById
      tags:
        - Reports
      parameters:
        - name: id
          in: path
          description: Report id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
  /reports/last:
    get:
      summary: Get last report
      description: Get last report
      responses:
        '200':
          description: OK
          schema:
            type: object
  /reports/avg/{hours}:
    get:
      summary: Get average report
      description: Get average report
      parameters:
        - name: hours
          in: path
          description: Hours
          required: true
          type: integer
      responses:
        '200':
          description: OK
          schema:
            type: object